// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zybnhmjtdyhhytgngvzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Ym5obWp0ZHloaHl0Z25ndnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MzU2NzMsImV4cCI6MjA1NjMxMTY3M30.apAWTpa37jFxlJGXnULEHdedC7Y5qoBIX3PztdSs_uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);